${{ cookiecutter.template_components.header }}
[build-system]
requires = ${{ cookiecutter.project_dependencies.python.build_deps }}
build-backend = "setuptools.build_meta"


todo: Get ssh key local, push to remote.