###AutoGeneratedDocument
# This file is automatically generated.
# Rerunning the packaging script will not respect your changes.
# If you wish to implement change do that within your config.yaml.

from setuptools import setup, find_packages


setup(
    name="sample_project",
    install_requires=['pyYaml>=6.0.1']
)
    